coop_tilleuls_forgot_password:
  resource: .
  type: coop_tilleuls_forgot_password
  prefix: '/forgot-password'


#coop_tilleuls_forgot_password.reset:
#    path:   '/api/forgot-password'
#    defaults:  { _controller:  coop_tilleuls_forgot_password.controller.forgot_password:resetPasswordAction}
#    methods:  [POST]