knp_snappy:
  pdf:
    enabled: true
    binary: "/usr/local/bin/wkhtmltopdf"
    options:
      encoding: 'UTF-8'
      margin-top: '30mm'
      margin-bottom: '30mm'
      margin-left: '10mm'
      margin-right: '10mm'
  image:
    enabled: true
    options:
      enable-local-file-access: true