framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        buses:
            command.bus:
                middleware:
                    - doctrine_close_connection
        routing:
            'App\Common\Messenger\EmailMessage': async
