# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: Diurne api
            description: "Diurne api"
            version: "1.0"
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                error:
                    type: object
                    properties:
                        code:
                            type: integer
                        message:
                            type: string
            responses:
                UnauthorizedError:
                    description: Bad credentials
                    content:
                        application/json:
                            schema:
                                allOf: [ $ref: '#/components/schemas/error' ]
                JwtTokenInvalid:
                    description: "JWT Token invalid, expired or not found"
                    content:
                        application/json:
                            schema:
                                allOf:
                                    - $ref: '#/components/schemas/error'
        security:
            - Bearer: [ ]
        paths:
            /forgot-password:
                post:
                    tags:
                        - User
                    description: Reset password, return a token.
                    parameters:
                        - in: query
                          name: email
                          description: Reset password
                          required: true
                          schema:
                              type: object
                              properties:
                                  email:
                                      type: string
                    responses:
                        '200':
                            description: Reset password successful, return a token with 1 day duration.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            $ref: '#/components/responses/UnauthorizedError'
            /forgot-password/{token}:
                post:
                    tags:
                        - User
                    description: Update password.
                    parameters:
                        - in: query
                          name: password
                          description: Update password
                          required: true
                          schema:
                              type: object
                              properties:
                                  password:
                                      type: string
                    responses:
                        '200':
                            description: Update password successful.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            user_id:
                                                type: string
                        '401':
                            $ref: '#/components/responses/UnauthorizedError'
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc